server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog
    username: rw_blog_account
    password: sndfvkajrgf9q274gf437G8348f^oo34gaw-089f
    driver-class-name: com.mysql.cj.jdbc.Driver
